# Generated by Django 3.1.7 on 2021-03-12 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0002_auto_20210311_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restfoodmodel',
            name='Menu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantApp.restmenumodel'),
        ),
        migrations.AlterField(
            model_name='restfoodmodel',
            name='restaurant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantApp.restaurantmodel'),
        ),
        migrations.AlterField(
            model_name='restmenumodel',
            name='restaurant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantApp.restaurantmodel'),
        ),
    ]
