# Generated by Django 3.1.7 on 2021-03-13 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0003_auto_20210312_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restfoodmodel',
            name='restaurant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='restaurantApp.restaurantmodel'),
        ),
    ]
