# Generated by Django 3.1.7 on 2021-03-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0004_auto_20210313_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmodel',
            name='rest_email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
