# Generated by Django 3.1.7 on 2021-03-27 10:38

from django.db import migrations, models
import restaurantApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0005_restaurantmodel_rest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmodel',
            name='rest_image',
            field=models.ImageField(blank=True, default='restaurants/default.jpg', null=True, upload_to=restaurantApp.models.upload_to, verbose_name='Image'),
        ),
    ]
