# Generated by Django 3.1.7 on 2021-03-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_remove_cartitem_restaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_restaurant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
